modules:
  - apps/android-app
  - apps/ios-app
  - apps/jvm-app
  - apps/shared
  - architecture-layer/data-layer/movie-data
  - architecture-layer/domain-layer/movie-domain
  - architecture-layer/presentation-layer/dashboard
  - base/navigation
